[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yew_ui_example"
path = "./src/main.rs"

[dependencies]
yew =  { workspace = true }
gloo = { workspace = true }
yew_ui = { path = "../core" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"