[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yew_ui_example"
path = "./src/main.rs"

[dependencies]
yew =  { workspace = true }
yew-ui = { path = "../core", features = ["gloo", "toolkit"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"